import Header from "@/components/Header";
import ResultCard from "@/components/ResultCard";
import styles from "@/constants/styles";
import { Image, ScrollView, Text, TouchableOpacity, View } from "react-native";
import Feather from "@expo/vector-icons/Feather";
import COLORS from "@/constants/colors";

const ResultScreen = ({
  imageUri,
  results,
  onReset,
}: {
  imageUri: string;
  results: { className: string; probability: number }[];
  onReset: () => void;
}) => (
  <View style={[styles.screen]}>
    <Header title="Classification Results" onBack={onReset} showBack />
    <ScrollView contentContainerStyle={styles.resultScreen}>
      <View style={styles.imagePreviewContainerSmall}>
        <Image source={{ uri: imageUri }} style={styles.imagePreview} />
      </View>
      <Text style={styles.resultsHeader}>Top Matches</Text>
      <View style={styles.resultsList}>
        {results.map((result, index) => (
          <ResultCard
            key={index}
            label={result.className}
            score={result.probability}
            isTopResult={index === 0}
          />
        ))}
      </View>
      <View
        style={{
          padding: 16,
          backgroundColor: "#f0f0f0",
          borderRadius: 8,
          marginTop: 16,
          flexDirection: "row",
          justifyContent: "space-between",
          alignItems: "center",
          gap: 10,
          width: "100%",
        }}
      >
        <Feather name="info" size={24} color={COLORS.red500} />
        <Text
          style={[
            styles.subtitle,
            { marginBottom: 0, textAlign: "justify", flexWrap: "wrap", flex: 1 },
          ]}
        >
          These results are generated by an AI model. Please use your own
          judgment to verify the results.
        </Text>
      </View>
      <TouchableOpacity
        style={[styles.buttonPrimary, { marginTop: 32 }]}
        onPress={onReset}
      >
        <Text style={styles.buttonTextPrimary}>Scan Another Image</Text>
      </TouchableOpacity>
    </ScrollView>
  </View>
);

export default ResultScreen;
